package pe.unjfsc.ads.java8.view;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import pe.unjfsc.ads.java8.entity.CE_Alternativa;

/**
 *
 * @author lenovo
 */
public class NewJFrame_Alternativa extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame_Alternativa
     */
    public NewJFrame_Alternativa() {
        initComponents();
        this.setLocationRelativeTo(null);

        CE_Alternativa objetomostar = new CE_Alternativa();
        objetomostar.Mostrar_CE_Alternativa(TABLA_ALTENATIVA);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jidpreg = new javax.swing.JTextField();
        jidalterna = new javax.swing.JTextField();
        jalterna = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jAdolescentess = new javax.swing.JComboBox<>();
        JGRABARR = new javax.swing.JButton();
        JMODIFICARR = new javax.swing.JButton();
        JELIMINARR = new javax.swing.JButton();
        JCERRARR = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLA_ALTENATIVA = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        GRAFICO1 = new javax.swing.JButton();
        GRAFICO2 = new javax.swing.JButton();
        GRAFICO3 = new javax.swing.JButton();
        GRAFICO4 = new javax.swing.JButton();
        GRAFICO5 = new javax.swing.JButton();
        GRAFICO6 = new javax.swing.JButton();
        GRAFICO7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Respuestas");

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 51, 0));
        jButton3.setText("X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingreso de Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Pregunta");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID alternativa");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alternativa");

        jButton13.setBackground(new java.awt.Color(0, 0, 0));
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Ver Preguntas");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Adolescentes");

        jAdolescentess.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Moreno Salas, Martha", "Ugarte Martinez, Elizabeth", "Campos Sanchez, Julia", "Baca Torres, Andreina ", "Cabello Camones, Daniela  ", "Arias Quispe, Luhana", "Mamani Jimenez, Delcy ", "Pedroso Pinedo, Paula", "Becerra Letona, Sofia", "Robles Diaz, Julisa", "Tamara Vera, Rosa", "Vega Quino , Jenny", "Sanchez Pardo,\tLuisa", "Verde Ponce, Camila ", "Sifuentes Leon,\tCarla", "Hilario Pozo, Ines", "Huerta Sanchez, Noelia", "Jara Capcha, Delia", "Pinedo Lopez, Lila", " ", " ", " ", " ", " " }));

        JGRABARR.setBackground(new java.awt.Color(0, 0, 0));
        JGRABARR.setForeground(new java.awt.Color(255, 255, 255));
        JGRABARR.setText("Guardar");
        JGRABARR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JGRABARRActionPerformed(evt);
            }
        });

        JMODIFICARR.setBackground(new java.awt.Color(0, 0, 0));
        JMODIFICARR.setForeground(new java.awt.Color(255, 255, 255));
        JMODIFICARR.setText("Editar");
        JMODIFICARR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMODIFICARRActionPerformed(evt);
            }
        });

        JELIMINARR.setBackground(new java.awt.Color(0, 0, 0));
        JELIMINARR.setForeground(new java.awt.Color(255, 255, 255));
        JELIMINARR.setText("Eliminar");
        JELIMINARR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JELIMINARRActionPerformed(evt);
            }
        });

        JCERRARR.setBackground(new java.awt.Color(0, 0, 0));
        JCERRARR.setForeground(new java.awt.Color(255, 255, 255));
        JCERRARR.setText("Cerrar");
        JCERRARR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCERRARRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jidpreg, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jidalterna, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jalterna, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JMODIFICARR)
                            .addComponent(JGRABARR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JELIMINARR)
                            .addComponent(JCERRARR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel5)
                        .addGap(53, 53, 53)
                        .addComponent(jAdolescentess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(39, 39, 39))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jButton13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jidpreg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JGRABARR)
                    .addComponent(JELIMINARR))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jidalterna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JMODIFICARR)
                        .addComponent(JCERRARR))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jalterna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAdolescentess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton13)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Acceso a servicios de planificacion familiar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(0, 0, 0));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Atención familiar\t");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton12)
                    .addComponent(jButton11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        TABLA_ALTENATIVA.setBackground(new java.awt.Color(0, 0, 0));
        TABLA_ALTENATIVA.setForeground(new java.awt.Color(255, 255, 255));
        TABLA_ALTENATIVA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Alternativa", "Id Pregunta", "Alternativa", "Adolescentes"
            }
        ));
        TABLA_ALTENATIVA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLA_ALTENATIVAMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TABLA_ALTENATIVA);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gráficos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        GRAFICO1.setBackground(new java.awt.Color(0, 0, 0));
        GRAFICO1.setForeground(new java.awt.Color(255, 255, 255));
        GRAFICO1.setText("Actividad sexual");
        GRAFICO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRAFICO1ActionPerformed(evt);
            }
        });

        GRAFICO2.setBackground(new java.awt.Color(0, 0, 0));
        GRAFICO2.setForeground(new java.awt.Color(255, 255, 255));
        GRAFICO2.setText("Acceso a redes sociales\t");
        GRAFICO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRAFICO2ActionPerformed(evt);
            }
        });

        GRAFICO3.setBackground(new java.awt.Color(0, 0, 0));
        GRAFICO3.setForeground(new java.awt.Color(255, 255, 255));
        GRAFICO3.setText("Conocimiento salud sexual");
        GRAFICO3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRAFICO3ActionPerformed(evt);
            }
        });

        GRAFICO4.setBackground(new java.awt.Color(0, 0, 0));
        GRAFICO4.setForeground(new java.awt.Color(255, 255, 255));
        GRAFICO4.setText("Interacciones en las red social\t");
        GRAFICO4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRAFICO4ActionPerformed(evt);
            }
        });

        GRAFICO5.setBackground(new java.awt.Color(0, 0, 0));
        GRAFICO5.setForeground(new java.awt.Color(255, 255, 255));
        GRAFICO5.setText("Cuenta con dispositivos electrónicos");
        GRAFICO5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRAFICO5ActionPerformed(evt);
            }
        });

        GRAFICO6.setBackground(new java.awt.Color(0, 0, 0));
        GRAFICO6.setForeground(new java.awt.Color(255, 255, 255));
        GRAFICO6.setText("Conocimiento ITS\t");
        GRAFICO6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRAFICO6ActionPerformed(evt);
            }
        });

        GRAFICO7.setBackground(new java.awt.Color(0, 0, 0));
        GRAFICO7.setForeground(new java.awt.Color(255, 255, 255));
        GRAFICO7.setText("Red social mas usada");
        GRAFICO7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRAFICO7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GRAFICO1)
                    .addComponent(GRAFICO2)
                    .addComponent(GRAFICO3)
                    .addComponent(GRAFICO4)
                    .addComponent(GRAFICO5)
                    .addComponent(GRAFICO6)
                    .addComponent(GRAFICO7))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(GRAFICO1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GRAFICO2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GRAFICO3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GRAFICO4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GRAFICO5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GRAFICO6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GRAFICO7)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        JDialog_Pregunta pregunta = new JDialog_Pregunta(this, rootPaneCheckingEnabled);
        pregunta.setVisible(true);

    }//GEN-LAST:event_jButton13ActionPerformed

    private void JCERRARRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCERRARRActionPerformed
         this.setVisible(false);
    NewJFrame_menu me = new NewJFrame_menu();
    me.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_JCERRARRActionPerformed

    private void GRAFICO7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRAFICO7ActionPerformed
        int Facebook = 6;
        int WhatsApp = 8;
        int Instagram = 3;
        int Otros = 3;
        String titulo = "Redes Sociales más usadas";

        try {
            DefaultCategoryDataset ds = new DefaultCategoryDataset();
            ds.addValue(Facebook, "Facebook", "");
            ds.addValue(WhatsApp, "WhatsApp", "");
            ds.addValue(Instagram, "Instagram", "");
            ds.addValue(Otros, "Otros", "");

            JFreeChart jf = ChartFactory.createBarChart("", "", titulo, ds, PlotOrientation.VERTICAL, true, true, true);
            ChartFrame f = new ChartFrame("", jf);
            f.setSize(500, 300);

            f.setLocationRelativeTo(null);
            f.setVisible(true);

        } catch (Exception e) {
        }

    }//GEN-LAST:event_GRAFICO7ActionPerformed

    private void GRAFICO6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRAFICO6ActionPerformed
         int si = 9;
        int no = 11;

        String titulo = "Conocimiento sobre la ITS";

        try {
            DefaultCategoryDataset ds = new DefaultCategoryDataset();
            ds.addValue(si, "SI", "");
            ds.addValue(no, "NO", "");
            JFreeChart jf = ChartFactory.createBarChart("", "", titulo, ds, PlotOrientation.VERTICAL, true, true, true);
            ChartFrame f = new ChartFrame("", jf);
            f.setSize(500, 300);

            f.setLocationRelativeTo(null);
            f.setVisible(true);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_GRAFICO6ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

         int si = 11;
        int no = 9;

        String titulo = "Acceso a servicios de planificacion familiar";

        try {
            DefaultCategoryDataset ds = new DefaultCategoryDataset();
            ds.addValue(si, "SI", "");
            ds.addValue(no, "NO", "");
            JFreeChart jf = ChartFactory.createBarChart("", "", titulo, ds, PlotOrientation.VERTICAL, true, true, true);
            ChartFrame f = new ChartFrame("", jf);
            f.setSize(500, 300);

            f.setLocationRelativeTo(null);
            f.setVisible(true);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        int si = 12;
        int no = 8;

        String titulo = "Cuenta con atencion familiar por parte de sus padres";

        try {
            DefaultCategoryDataset ds = new DefaultCategoryDataset();
            ds.addValue(si, "SI", "");
            ds.addValue(no, "NO", "");
            JFreeChart jf = ChartFactory.createBarChart("", "", titulo, ds, PlotOrientation.VERTICAL, true, true, true);
            ChartFrame f = new ChartFrame("", jf);
            f.setSize(500, 300);

            f.setLocationRelativeTo(null);
            f.setVisible(true);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void GRAFICO4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRAFICO4ActionPerformed
         int si = 14;
        int no = 6;

        String titulo = " Interactua en las redes sociales";

        try {
            DefaultCategoryDataset ds = new DefaultCategoryDataset();
            ds.addValue(si, "SI", "");
            ds.addValue(no, "NO", "");
            JFreeChart jf = ChartFactory.createBarChart("", "", titulo, ds, PlotOrientation.VERTICAL, true, true, true);
            ChartFrame f = new ChartFrame("", jf);
            f.setSize(500, 300);

            f.setLocationRelativeTo(null);
            f.setVisible(true);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_GRAFICO4ActionPerformed

    private void GRAFICO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRAFICO1ActionPerformed
        int si = 8;
        int no = 12;

        String titulo = " Actividad Sexual";

        try {
            DefaultCategoryDataset ds = new DefaultCategoryDataset();
            ds.addValue(si, "SI", "");
            ds.addValue(no, "NO", "");
            JFreeChart jf = ChartFactory.createBarChart("", "", titulo, ds, PlotOrientation.VERTICAL, true, true, true);
            ChartFrame f = new ChartFrame("", jf);
            f.setSize(500, 300);

            f.setLocationRelativeTo(null);
            f.setVisible(true);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_GRAFICO1ActionPerformed

    private void GRAFICO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRAFICO2ActionPerformed
         int si = 13;
        int no = 7;

        String titulo = "  mantiene actividad sexual ";

        try {
            DefaultCategoryDataset ds = new DefaultCategoryDataset();
            ds.addValue(si, "SI", "");
            ds.addValue(no, "NO", "");
            JFreeChart jf = ChartFactory.createBarChart("", "", titulo, ds, PlotOrientation.VERTICAL, true, true, true);
            ChartFrame f = new ChartFrame("", jf);
            f.setSize(500, 300);

            f.setLocationRelativeTo(null);
            f.setVisible(true);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_GRAFICO2ActionPerformed

    private void GRAFICO3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRAFICO3ActionPerformed
          int si = 9;
        int no = 11;

        String titulo = "conocimiento sobre la salud sexual";

        try {
            DefaultCategoryDataset ds = new DefaultCategoryDataset();
            ds.addValue(si, "SI", "");
            ds.addValue(no, "NO", "");
            JFreeChart jf = ChartFactory.createBarChart("", "", titulo, ds, PlotOrientation.HORIZONTAL, true, true, true);
            ChartFrame f = new ChartFrame("", jf);
            f.setSize(500, 300);

            f.setLocationRelativeTo(null);
            f.setVisible(true);

        } catch (Exception e) {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_GRAFICO3ActionPerformed

    private void GRAFICO5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRAFICO5ActionPerformed
        int si = 13;
        int no = 7;

        String titulo = "cuenta con dispositivos electronicos";

        try {
            DefaultCategoryDataset ds = new DefaultCategoryDataset();
            ds.addValue(si, "SI", "");
            ds.addValue(no, "NO", "");
            JFreeChart jf = ChartFactory.createBarChart("", "", titulo, ds, PlotOrientation.VERTICAL, true, true, true);
            ChartFrame f = new ChartFrame("", jf);
            f.setSize(500, 300);

            f.setLocationRelativeTo(null);
            f.setVisible(true);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_GRAFICO5ActionPerformed

    private void JGRABARRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JGRABARRActionPerformed
        CE_Alternativa objALTER = new CE_Alternativa();
        objALTER.Insertar_CE_ALTERNA(jidalterna, jidpreg, jalterna, jAdolescentess);
        objALTER.Mostrar_CE_Alternativa(TABLA_ALTENATIVA);
    }//GEN-LAST:event_JGRABARRActionPerformed

    private void JMODIFICARRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMODIFICARRActionPerformed
       CE_Alternativa objALTER = new CE_Alternativa();
       objALTER.Modificar_CE_Alternativa(jidalterna, jidpreg, jalterna);
       objALTER.Mostrar_CE_Alternativa(TABLA_ALTENATIVA);
    }//GEN-LAST:event_JMODIFICARRActionPerformed

    private void JELIMINARRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JELIMINARRActionPerformed
       CE_Alternativa objALTER = new CE_Alternativa();
       objALTER.Eliminar_CE_Alternativa(jidalterna);
       objALTER.Mostrar_CE_Alternativa(TABLA_ALTENATIVA);
    }//GEN-LAST:event_JELIMINARRActionPerformed

    private void TABLA_ALTENATIVAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLA_ALTENATIVAMouseClicked
        CE_Alternativa objetALtern = new CE_Alternativa();
        objetALtern.SelecionarTabla(TABLA_ALTENATIVA, jidalterna, jidpreg, jalterna);
        
        
    }//GEN-LAST:event_TABLA_ALTENATIVAMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_Alternativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_Alternativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_Alternativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_Alternativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame_Alternativa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GRAFICO1;
    private javax.swing.JButton GRAFICO2;
    private javax.swing.JButton GRAFICO3;
    private javax.swing.JButton GRAFICO4;
    private javax.swing.JButton GRAFICO5;
    private javax.swing.JButton GRAFICO6;
    private javax.swing.JButton GRAFICO7;
    private javax.swing.JButton JCERRARR;
    private javax.swing.JButton JELIMINARR;
    private javax.swing.JButton JGRABARR;
    private javax.swing.JButton JMODIFICARR;
    private javax.swing.JTable TABLA_ALTENATIVA;
    private javax.swing.JComboBox<String> jAdolescentess;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jalterna;
    private javax.swing.JTextField jidalterna;
    private javax.swing.JTextField jidpreg;
    // End of variables declaration//GEN-END:variables
}
